# fly.toml app configuration file generated for vilatur on 2023-07-08T18:32:47-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vilatur"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
